name: Lacework Code Security (Pull Request)

on:
  pull_request:
    branches:
      - main

env:
  LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
  LW_API_KEY: ${{ secrets.LW_API_KEY }}
  LW_API_SECRET: ${{ secrets.LW_API_SECRET }}

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    name: Run analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Analyze
        uses: lacework/code-security-action@v1
        with:
          target: pullRequest